apiVersion: kubedb.com/v1
kind: MySQL
metadata:
  annotations:
    app.kubernetes.io/cluster-tier: GeneralPurpose
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubedb.com/v1","kind":"MySQL","metadata":{"annotations":{"app.kubernetes.io/cluster-tier":"GeneralPurpose","meta.helm.sh/release-name":"mys-tls","meta.helm.sh/release-namespace":"demo"},"labels":{"app.kubernetes.io/instance":"mys-tls","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"mysqls.kubedb.com"},"name":"mys-tls","namespace":"demo"},"spec":{"deletionPolicy":"WipeOut","monitor":{"agent":"prometheus.io/operator","prometheus":{"exporter":{"resources":{"limits":{"memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"runAsGroup":0,"runAsNonRoot":true,"runAsUser":999,"seccompProfile":{"type":"RuntimeDefault"}}},"serviceMonitor":{"interval":"30s","labels":{"release":"kube-prometheus-stack"}}}},"podTemplate":{"spec":{"containers":[{"name":"mysql","resources":{"limits":{"cpu":"500m","memory":"1536Mi"},"requests":{"cpu":"500m","memory":"1536Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"runAsGroup":0,"runAsNonRoot":true,"runAsUser":999,"seccompProfile":{"type":"RuntimeDefault"}}},{"name":"mysql-coordinator","resources":{"limits":{"memory":"256Mi"},"requests":{"cpu":"200m","memory":"256Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"runAsGroup":0,"runAsNonRoot":true,"runAsUser":999,"seccompProfile":{"type":"RuntimeDefault"}}}],"initContainers":[{"name":"mysql-init","resources":{"limits":{"memory":"512Mi"},"requests":{"cpu":"200m","memory":"256Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"runAsGroup":0,"runAsNonRoot":true,"runAsUser":999,"seccompProfile":{"type":"RuntimeDefault"}}}],"nodeSelector":{"kubernetes.io/os":"linux"},"securityContext":{"fsGroup":999}}},"replicas":3,"requireSSL":true,"storage":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"2Gi"}},"storageClassName":"local-path"},"storageType":"Durable","tls":{"issuerRef":{"apiGroup":"cert-manager.io","kind":"ClusterIssuer","name":"cluster-issuer"}},"topology":{"mode":"GroupReplication"},"version":"8.0.36"}}
    meta.helm.sh/release-name: mys-tls
    meta.helm.sh/release-namespace: demo
  creationTimestamp: "2025-03-27T08:13:31Z"
  finalizers:
  - kubedb.com
  generation: 2
  labels:
    app.kubernetes.io/instance: mys-tls
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysqls.kubedb.com
  name: mys-tls
  namespace: demo
  resourceVersion: "283450"
  uid: 3790c0de-cff0-4ea0-a7ba-7e832f5f2bf6
spec:
  allowedReadReplicas:
    namespaces:
      from: Same
  allowedSchemas:
    namespaces:
      from: Same
  authSecret:
    name: mys-tls-auth
  autoOps: {}
  deletionPolicy: WipeOut
  healthChecker:
    failureThreshold: 1
    periodSeconds: 10
    timeoutSeconds: 10
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        port: 56790
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 0
          runAsNonRoot: true
          runAsUser: 999
          seccompProfile:
            type: RuntimeDefault
      serviceMonitor:
        interval: 30s
        labels:
          release: kube-prometheus-stack
  podTemplate:
    controller: {}
    metadata: {}
    spec:
      containers:
      - name: mysql
        resources:
          limits:
            cpu: 500m
            memory: 1536Mi
          requests:
            cpu: 500m
            memory: 1536Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 0
          runAsNonRoot: true
          runAsUser: 999
          seccompProfile:
            type: RuntimeDefault
      - name: mysql-coordinator
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 0
          runAsNonRoot: true
          runAsUser: 999
          seccompProfile:
            type: RuntimeDefault
      initContainers:
      - name: mysql-init
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 0
          runAsNonRoot: true
          runAsUser: 999
          seccompProfile:
            type: RuntimeDefault
      nodeSelector:
        kubernetes.io/os: linux
      podPlacementPolicy:
        name: default
      securityContext:
        fsGroup: 999
      serviceAccountName: mys-tls
  replicas: 3
  requireSSL: true
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-path
  storageType: Durable
  tls:
    certificates:
    - alias: server
      secretName: mys-tls-server-cert
    - alias: client
      secretName: mys-tls-client-cert
    - alias: metrics-exporter
      secretName: mys-tls-metrics-exporter-cert
    issuerRef:
      apiGroup: cert-manager.io
      kind: ClusterIssuer
      name: cluster-issuer
  topology:
    group:
      mode: Single-Primary
      name: d716a0c1-084e-436f-b701-de1d21e55c6b
    mode: GroupReplication
  useAddressType: DNS
  version: 8.0.36
status:
  conditions:
  - lastTransitionTime: "2025-03-27T08:13:32Z"
    message: 'The KubeDB operator has started the provisioning of MySQL: demo/mys-tls'
    reason: DatabaseProvisioningStartedSuccessfully
    status: "True"
    type: ProvisioningStarted
  - lastTransitionTime: "2025-03-27T08:13:59Z"
    message: All desired replicas are ready.
    reason: AllReplicasReady
    status: "True"
    type: ReplicaReady
  - lastTransitionTime: "2025-03-27T08:14:39Z"
    message: database demo/mys-tls is accepting connection
    observedGeneration: 2
    reason: AcceptingConnection
    status: "True"
    type: AcceptingConnection
  - lastTransitionTime: "2025-03-27T08:14:39Z"
    message: database demo/mys-tls is ready
    observedGeneration: 2
    reason: AllReplicasReady
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-03-27T08:14:44Z"
    message: 'The MySQL: demo/mys-tls is successfully provisioned.'
    observedGeneration: 2
    reason: DatabaseSuccessfullyProvisioned
    status: "True"
    type: Provisioned
  observedGeneration: 2
  phase: Ready
